### ISSUE TITLE
[QUESTION] How to handle long startup times on the first request

### ISSUE THREAD

**Issue by nusje2000** [symfony/panther#211]
I started using panther inside my symfony project, and when I start a unit test, the first call made by the HTTP client to check if the webserver is running will build the cache. This takes more than 5 seconds and thus the process will fail due to "Could not connect to chrome after 5 seconds (Reading from the response stream reached the inactivity timeout.)". The current solution I have is setting the readinessPath to a file that is present in the web directory so it can be served directly (in my case that is "robots.txt"). I don't know if this is a correct solution. Is it possible to increase the connectivity timeout through some form of config ?

Other advise for handling long startup times are welcome as well.

**Comment by stof** [comment]
Well, what you can do is warming up the cache before starting your tests.

But `Could not connect to chrome after 5 seconds` does not seem to be the cache for whether the webserver is running (otherwise, it would say `could not connect to web server`), but whether chromedriver is running. So this looks unrelated to the Symfony cache.

**Comment by nusje2000** [comment]
I found that the problem was in the fact that to check the availability of the webserver, panther uses a HTTP call to the webserver host (i.e. localhost:9080). When this call is made, it will try to build the cache because the request is handled by symfony. But I've added a cache warmup to my build script and it seems to give a response within the given timeout of 5 seconds. Thank you :+1:
