### ISSUE TITLE
PhpUnit Bridge not working

### ISSUE THREAD

**Issue by ymc-sise** [symfony/panther#345]
I want to use ClockMock to mock time() in Panther Tests using a headless chrome. Unfortunately it does not work with Panther. If I use a WebTestCase everything works fine with mocking time. Is there any chance to enable this feature?

**Comment by domis86** [comment]
It does not work because if you use headless chrome then you are doing request to different instance of application (separate request to server) - there everything is started from scratch, so any mocks you set in your tests are no longer loaded. Is like you would browse page via browser.

To take control over date / time in such request you need to use some different mechanism - for example: use db. It would work like this:
1. Before request you will save desired date and time in some place in db (some new dedicated table "datetime_mock" etc).
2. Also prepare a symfony kernel listener to listen on https://symfony.com/doc/current/reference/events.html#kernel-request - it would load info mentioned in previous point from db table and setup ClockMock using it.
    * remember to setup this listener only for desired environment ("test" env?) - so it wont affect behaviour of "prod" env.
3. Now when you execute request using panther in your test then the appplication instance will use desired date and time mock correctly.
4. In "tearDown" method in your test class make sure that data from table from point 1 ("datetime_mock") is cleared.

**Comment by ymc-sise** [comment]
Many thanks for showing your idea. Great! In my case it seems a bit too much and I simply avoid to test the time.
