### ISSUE TITLE
Undefined class constant 'CHROME'

### ISSUE THREAD

**Issue by aurelijusrozenas** [symfony/panther#384]
Hi,

Symfony 4.4 fails when using `PantherTestCaseTrait`:

> Undefined class constant 'CHROME'

I see https://github.com/symfony/panther/issues/317 and that it is merged but the error is still happening (starting with 0.7.0 and to the latest).
I created a reproducible example https://github.com/aurelijusrozenas/panther-test

The test code taken from example and is minimal: https://github.com/aurelijusrozenas/panther-test/blob/main/tests/DefaultTest.php

Any ideas? I would say it's a bug but how come no one has reported yet? :)

**Comment by HonzaMatosik** [comment]
Hello @aurelijusrozenas,

these constants are defined in `PantherTestCase` which extends standard Symfony `WebTestCase` (https://github.com/symfony/panther/blob/main/src/PantherTestCase.php). You need to extend your tests from `PantherTestCase` instead of `WebTestCase` to make class constants accessible in your test.

btw: Thank you for preparing example repository with minimal code and docker-compose setup. It was very easy to test my solution.

**Comment by aurelijusrozenas** [comment]
Hi @HonzaMatosik, thanks for looking at it.
But wouldn't you say that `PantherTestCaseTrait` is exactly for my case? We extend different base class which itself extend WebTestCase so trait usage is preferable. And since it was working before I would say it's a bug :beetle:

**Comment by nusje2000** [comment]
The constant is used in the trait and should not depend on the class that the trait is used in. I would say that this constant should either be moved to a separate class, or be moved to the trait. I think this should indeed be marked as a bug.

@aurelijusrozenas I encountered this problem as well when I implemented panther. The project I work on required a more custom implementation so I used the trait as well instead of the PantherTestCase. I copied the constants to the implementation and that did work, but is not the prefered method I would say.
